config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # next line added 19 may 17
  root 'places#index'
  # next line added 22 may 17, "do" added 26 may 17
  resources :places do
 # next line added 26 may 17
    resources :comments, only: :create
    
  # next line added 1 jun 17 for photos - lesson 39 (challenge)
    resources :photos, only: :create
    
  end
  
  # next line added 29 may 17 for user show page
  resources :users, only: :show
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
# next 2 lines added 26 may 17 - connects comment with a user and place
    belongs_to :user
    belongs_to :place
    
# next line added 28 may 17 - for triggering email notification after comment created
    after_create :send_comment_email
    
# next 10 lines added 26 may 17 - for dropdown for star ratings
    RATINGS = {
        'one star': '1_star',
        'two stars': '2_stars',
        'three stars': '3_stars',
        'four stars': '4_stars',
        'five stars': '5_stars'
    }
    
    def humanized_rating
        RATINGS.invert[self.rating]
    end

# next 3 lines added 28 may 17 - for triggering email notification after comment created
    def send_comment_email
        NotificationMailer.comment_added(self).deliver
    end
end

app/models/photo.rb
class Photo < ApplicationRecord
    
# next 2 lines added 1 jun 17 - connects photo with a user and place for lesson 39 (challenge)
#    belongs_to :user
    belongs_to :place

# next line added 2 jun 17 - mounts uploader for lesson 39 (challenge)
    mount_uploader :picture, PictureUploader
    
end

app/models/place.rb
class Place < ApplicationRecord

# next line added 22 may 17
    belongs_to :user
    
# next line added 26 may 17
    has_many :comments
    
# next line added 1 jun 17 for lesson 39 (challenge)
    has_many :photos
    
# next 2 line added 24 may 17; allows use of geocoding
    geocoded_by :address
    after_validation :geocode
    
# next 2 line added 24 may 17; ensure no one enters blanks for any field, name > 3 chars
    validates :name, presence: true, length: {minimum: 4}
    validates :address, :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

# next line added 22 may 17
  has_many :places
  
# next line added 26 may 17
  has_many :comments
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
# firehose track 3, lesson 33 - file created 26 may 17

class CommentsController < ApplicationController
    before_action :authenticate_user!
    
    def create
        @place = Place.find(params[:place_id])
        @place.comments.create(comment_params.merge(user: current_user))
        redirect_to place_path(@place)
    end
    
    private
    
    def comment_params
        params.require(:comment).permit(:message, :rating)
    end
end

app/controllers/photos_controller.rb
# firehose track 3, lesson 39 (challenge) - file created 1 jun 17

class PhotosController < ApplicationController
    before_action :authenticate_user!
    
    def create
        @place = Place.find(params[:place_id])
#        byebug                                  # stops execution, shows state
        @place.photos.create(photo_params)
#        @place.photos.create(photo_params.merge(user: current_user))
        redirect_to place_path(@place)
    end
    
# next lines added so only place creator can destroy photos
    def destroy
        @place = Place.find(params[:id])
        if @place.user != current_user
            return render plain: 'Not Allowed', status: :forbidden
        end
        @place.photos.destroy(photo_params)
        redirect_to root_path
    end


    private
    
    def photo_params
        params.require(:photo).permit(:picture, :caption)
    end

end

app/controllers/places_controller.rb
# file created 19 may 17
class PlacesController < ApplicationController
# next line added 22 may 17, modified 23 may 17
    before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
    
    def index
# next line added 20 may 17, modified to paginate 30 may 17 (challenge/lesson 12) using will_paginate
        @places = Place.paginate(:page => params[:page], :per_page => 10)
    end

# next 7 lines added 22 may 17
    def new
        @place = Place.new
    end
    
    def create
# next 6 lines modified/added 24 may 17 to prevent blank place name
        @place = current_user.places.create(place_params)
        if @place.valid?
            redirect_to root_path
        else
            render :new, status: :unprocessable_entity
        end
    end

# next 19 lines added 23 may 17
    def show
        @place = Place.find(params[:id])
        
# next line added 26 may 17
        @comment = Comment.new

# next line added 3 jun 17 for lesson 39 (challenge)
        @photo = Photo.new
    end
    
    def edit
        @place = Place.find(params[:id])
        
        if @place.user != current_user
            return render plain: 'Not Allowed', status: :forbidden
        end
    end
    
    def update
        @place = Place.find(params[:id])
        if @place.user != current_user
            return render plain: 'Not Allowed', status: :forbidden
        end
        @place.update_attributes(place_params)
# next 5 lines modified/added 24 may 17 to prevent blank place name
        if @place.valid?
            redirect_to root_path
        else
            render :edit, status: :unprocessable_entity
        end
    end
    
    def destroy
        @place = Place.find(params[:id])
        if @place.user != current_user
            return render plain: 'Not Allowed', status: :forbidden
        end
        @place.destroy
        redirect_to root_path
    end
    
# next 4 lines added 22 may 17
    private
    
    def place_params
        params.require(:place).permit(:name, :description, :address)
    end

end

app/controllers/users_controller.rb
# firehose track 3, lesson 47 - file created 29 may 17

class UsersController < ApplicationController
    def show
        @user = User.find(params[:id])  # load user info from database for user w/id passed
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nomster</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- next 23 lines (navbar) added/modified 21 may 17 -->
    <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
<!--      <a class="navbar-brand" href="#">Nomster</a>  -->
<!-- next line added 22 may 17 -->
      <%= link_to 'Nomster', root_path, class: 'navbar-brand' %>

      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-md-0">
<!--          <li class="nav-item active">       
          <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>  -->
          <li class="nav-item">
<!--            <a class="nav-link" href="#">Link</a>  -->
<!-- next 3 lines added 22 may 17, ruby way of doing the <a> link above, and plus -->
<!--            <%= link_to 'New Place', new_place_path, class: 'nav-link' %>  -->
            <%= link_to new_place_path, class: 'nav-link' do %>
              <i class="fa fa-plus-circle"></i>
              New Place
            <% end %>
          </li>
          
<!--          <li class="nav-item">
            <a class="nav-link disabled" href="#">Disabled</a>
          </li>  -->
        </ul>
        
<!--        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>  -->
        
<!-- lines added 22 may 17  -->
        <ul class="navbar-nav">
          <% if user_signed_in? %>
<!-- next 3 lines added 29 may 17 for user show page -->
          <li class="nav-item">
            <%= link_to 'My Profile', user_path(current_user), class: 'nav-link' %>
          </li>
          <li class="nav-item">
<!--              <%= link_to 'A user is signed in!', '#', class: 'nav-link' %>  -->
              <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
          </li>
          <% else %>
          <li class="nav-item">
<!--              <%= link_to 'No user is signed in :(', '#', class: 'nav-link' %>  -->
              <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
              <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
          </li>
          <% end %>
        </ul>
        
      </div>
    </nav>
    
<!-- next 2 lines added/modified 22 may 17 -->
<!--    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>  -->
    <% if notice.present? %>
      <p class="alert alert-info"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/places/edit.html.erb
<!-- firehose track 3, lesson 22 - file created 23 may 17 -->

<div class="booyah-box col-10 offset-1">
    <h1>Edit Your Place</h1>
    <br />
    <%= simple_form_for @place do |f| %>
        <%= f.input :name %>
        <br />
        <%= f.input :address %>
        <br />
        <%= f.input :description %>
        <br />
        <%= f.submit 'Update', class: 'btn btn-primary' %>
    <% end %>
</div>

app/views/places/index.html.erb
<!-- firehose track 3, lesson 4 - file created 19 may 17/modified 20-22 may 17 -->

<!-- <h1>Welcome to ET's awesome app</h1> -->
<!-- <h1><%= @places.inspect %></h1> -->

<!-- this code block added 29 may 17 for adding carousel -->
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
<!-- next line commented out since only 2 images for now; need one line like this per image -->
<!--        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>  -->
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="carousel-item active">
<!--            <img class="d-block img-fluid" src="..." alt="First slide">  -->
            <%= image_tag "slider1.jpg", class: "d-block img-fluid" %>
            <div class="carousel-caption d-none d-md-block">
                <h3>Toscanini's is the Best!</h3>
            </div>
        </div>
        <div class="carousel-item">
<!--            <img class="d-block img-fluid" src="..." alt="Second slide">  -->
            <%= image_tag "slider2.jpg", class: "d-block img-fluid" %>
            <div class="carousel-caption d-none d-md-block">
                <h3>Tasty!</h3>
            </div>
        </div>
        
<!-- next 3 lines commented out since only 2 images for now; need one block like this per image -->
<!--        <div class="carousel-item">
            <img class="d-block img-fluid" src="..." alt="Third slide">
        </div>  -->
        
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>


<% @places.each do |place| %>
    <div class="booyah-box col-10 offset-1">
        <h1><%= link_to place.name, place_path(place) %></h1><br />
        <i><%= place.address %></i><br /><br />
        <p><%= place.description %></p><br />
        
        <% if place.user.present? %>
          <small><%= place.user.email %></small>
        <% end %>
        
<!-- next 11 lines added 28 may 17 - shows last comment from each place on homepage -->
        <% if place.comments.present? %>     <!-- checks if comments exist, so no error  -->
            <div class="col-12">
                <blockquote>    <!-- show last comment for each place -->
                    <% if place.comments.last.humanized_rating.present? %>
                        <b><%= place.comments.last.humanized_rating %></b> -
                    <% end %>
                    <%= place.comments.last.message %>
                    <small><%= place.comments.last.user.email %></small>
                </blockquote>
            </div>
        <% end %>

<!-- next 3 lines added 9-11 jun 17 for showing first photo from each place on homepage (part of fine tuning) -->
        <% if place.photos.present? %>       <!-- checks if photos exist, so no error  -->
          <%= image_tag place.photos.first.picture %>
        <% end %>

    </div>
<!--  <hr />  -->
<% end %>

<!--  added 31 may 17 for pagination challenge (lesson 12) -->
<%= will_paginate @places %>

app/views/places/new.html.erb
<!-- firehose track 3, lesson 13 - file created 22 may 17 -->

<div class="booyah-box col-10 offset-1">
    <h1>Enter Your Place Details</h1>
    <br />
    <%= simple_form_for @place do |f| %>
        <%= f.input :name %>
        <br />
        <%= f.input :address %>
        <br />
        <%= f.input :description %>
        <br />
        <%= f.submit 'Create', class: 'btn btn-primary' %>
    <% end %>
</div>

app/views/places/show.html.erb
<!-- firehose track 3, lesson 21 - file created 23 may 17, modified 24-26 may 17 -->

<!-- <h1>Welcome to the show page</h1>  -->

<div class="booyah-box col-10 offset-1">
    <h1><%= @place.name %></h1>         <!-- display name -->
    <i><%= @place.address %></i>        <!-- display address -->
    <br/><br/>
    <p><%= @place.description %></p>    <!-- display description -->

    <% if @place.latitude.present? && @place.longitude.present? %>     <!-- display map is coords exist -->

        <script>
        
        function initMap() {
            var myLatLng = {lat: <%= @place.latitude %>, lng: <%= @place.longitude %>};
            
            var map = new google.maps.Map(document.getElementById('map'), {
                zoom: 12,
                center: myLatLng
            });
            
            var marker = new google.maps.Marker({
                position: myLatLng,
                map: map,
              title: 'Hello World!'
            });
        }
        </script>
        
        <script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCGTPAovnpVRgIyuLc8TMvCjUThCfgY7PY&callback=initMap">
        </script>
        
        <div id="map"></div>
    <% end %>

<br />

    <div class="float-right">
        <% if current_user && current_user == @place.user %>     <!-- so only place creator can edit/destroy place -->
            <%= link_to 'Edit', edit_place_path(@place), class: 'btn btn-primary' %>
            <%= link_to 'Destroy', place_path(@place), method: :delete, data: {confirm: 'Are you sure you want to delete this?'}, class: 'btn btn-danger' %>
        <% end %>
    </div>


<!-- next lines added 26 may 17 re: adding comment form, displaying comments -->
<div class="clear"></div>

<!-- Modal/pop-up for comments -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">Add a comment</h4>
            </div>
            
<!--            <div class="modal-body">
                <%= simple_form_for @comment, url: place_comments_path(@place) do |f| %>
                    <%= f.input :message %>
                    <%= f.input :rating, as: :select, collection: Comment::RATINGS %>  for dropdown star ratings
                    <%= f.submit "Add a Comment", class: 'btn btn-primary' %>
                <% end %>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>  -->
            
            <%= simple_form_for @comment, url: place_comments_path(@place) do |f| %>
                <div class="modal-body">
                    <%= f.input :message %>
                    <%= f.input :rating, as: :select, collection: Comment::RATINGS %>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <%= f.submit "Add a Comment", class: 'btn btn-primary' %>
                </div>
            <% end %>
        </div>
    </div>
</div>

<!-- next line added 27 may 17 -->
<div class="col-10 offset-1">
    
    <h1 class="float-left">Comments</h1>    <!-- Comments heading -->

<!-- next 5 lines added 27 may 17 -->
<!-- Button trigger modal for comments -->
    <button type="button" class="btn btn-primary btn-lg float-right" data-toggle="modal" data-target="#myModal">
        Add a comment
    </button>
</div>

<div class="clear"></div>

<!-- next lines added 27 may 17 for displaying comments on place show page -->
<div class="row">
    <% @place.comments.each do |comment| %>
        <div class="col-12 col-sm-6">
            <blockquote>
                
<!--            <b><%= comment.rating %></b> -
                <%= comment.message %>
            <small><%= comment.user.email %></small>  -->
            
<!-- next 5 lines added 26 may 17 for star ratings  -->
                <% if comment.humanized_rating.present? %>
                    <b><%= comment.humanized_rating %></b> -     <!-- display rating -->
                <% end %>
                <%= comment.message %>                           <!-- display comment -->
                <small><%= comment.user.email %></small>         <!-- display email address -->
            </blockquote>
        </div>
    <% end %>
</div>


<!-- next lines added 1 jun 17 re: adding photo form, displaying photos - lesson 39 (challenge) -->
<div class="clear"></div>

<div class="float-right">
    <% if current_user && current_user == @place.user %>     <!-- so only place creator can add photos -->
    
<!-- Button trigger modal for photos -->
        
        <button type="button" class="btn btn-primary btn-lg float-right" data-toggle="modal" data-target="#photoModal">
            Add a photo
        </button>

<!-- add method so only place creator can destroy photos -->

    <% end %>
    
<!-- </div>  -->
      
<!-- Modal/pop-up for photos -->
  <div class="modal fade" id="photoModal" tabindex="-1" role="dialog" aria-labelledby="photoModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title" id="photoModalLabel">Add a photo</h4>
            </div>

<!-- next lines added 2-4 jun 17 re: adding photo form, displaying photos - lesson 39 (challenge) -->
            <%= simple_form_for @photo, url: place_photos_path(@place) do |f| %>
                <div class="modal-body">
                    <%= f.input :picture %>
                    <%= f.input :caption %>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <%= f.submit "Add a Photo", class: 'btn btn-primary' %>
                </div>
            <% end %>

        </div>
    </div>
  </div>

</div>

<div class="col-10 offset-1">

    <h1 class="float-left">Photos</h1>

</div>


<!-- next 4 lines added 3 jun 17 for displaying photos - lesson 39 (challenge) -->
<% @place.photos.each do |photo| %>
    <%= image_tag photo.picture %>
    <%= photo.caption %>
<% end %>

</div>   <!-- close booyah-box -->

app/views/users/show.html.erb
<!-- firehose track 3, lesson 47 - file created 29 may 17 -->

<div class="booyah-box">
    <div class="row">
        <div class="col-4">     <!-- avatar on left side -->
            <%= image_tag "user.png" %>     <!-- avatar -->
        </div>
        
        <div class="col-8" style="text-align: right">
            <h1><%= @user.email %></h1>     <!-- metrics on right side -->
            <h3>Member Since: <%= @user.created_at.strftime("%d %B %Y") %></h3>
            <h4><%= @user.comments.count %> total comments</h4>
            <h4><%= @user.comments.where(rating: "5_stars").count %> total 5-star reviews</h4>
        </div>
    </div>
    <div class="clear"></div>
</div>

<!-- next lines added 30 may 17 -->
<br /><br />
<h1 class="text-center">My Comments</h1>
<br /><br />
<div class="row">
    <% @user.comments.each do |comment| %>
<!--    <%= comment.inspect %>  -->
        <div class="col-12 col-sm-6">
            <h2 class="text-center"><%= link_to comment.place.name, place_path(comment.place) %></h2>
            <blockquote>
                <% if comment.humanized_rating.present? %>
                    <b><%= comment.humanized_rating %></b> -
                <% end %>
                <%= comment.message %>
                <small><%= comment.user.email %></small>
            </blockquote>
        </div>
    <% end %>
</div>

<!-- next lines added 30 may 17 -->
<div class="clear"></div>
<br /><br />
<h2 class="text-center">My Places</h2>
<br /><br />
<% @user.places.each do |place| %>
    <div class="booyah-box col-10 offset-1">
        <h1><%= link_to place.name, place_path(place) %></h1><br />
        <i><%= place.address %></i><br />
        <p><%= place.description %></p><br />
        
        <% if place.user.present? %>
            <small><%= place.user.email %></small>
        <% end %>
        
        <% if place.comments.present? %>
            <div class="col-12">
                <blockquote>
                    <% if place.comments.last.humanized_rating.present? %>
                        <b><%= place.comments.last.humanized_rating %></b> -
                    <% end %>
                    <%= place.comments.last.message %>
                    <small><%= place.comments.last.user.email %></small>
                </blockquote>
            </div>
        <% end %>
    </div>
<% end %>